apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-basic-auth-token
  namespace: cicd
spec:
  encryptedData:
    password: AgCsl+ItJdl9JBno8vV9i4teeaRlFVTxpsWgszKX4RHBGUTXQ+DsqQe1MPEimnd6puPPr6560tvJl2YckLhtxhsK3Wamez4TIxs5vQD3ZcVuI01RLS4EugWnKIHGn1gKSHd9/g8ehhbYvJzLFIfeXZ8OeqBKqQ5DWZYCH7WO8c36uXveNARqyGLxYfQYQOrgJy4PidxrTGyez2gA3DOGKcL2nw2F6Wd22FQdNclEBsdniwTbNVXoz2qKYJLj8xmRRlkHXlj/TeVeC29O0DOtkrs8cfeK7MFP/oOnrY+sk8RMkZmNg3ObcNbmerpqs91IrkEwM3UMd3qC+uqxULkDbdUg2g1ygIxCnkUPbAgB74ZEwHvt17PJycd0wKIRaFRIS2Wsl2iWKi2fitRGLT2eiKy7kkMWP/bbwNBebkkia50rM4n98X5VHtds1YYdW+p867PZSV7UqWorCpgPMf5q/7ASliOI8AGmIGTFMSXcRJPZg6OTo9P87kM+I0DKHgcr8l3PPgWv2lhROqZcRacnphEaT1DDsdnQicPTzcF1Qr1oQdIWwrPW52YlGEO2j2VoBmA0xVDLyKMCZfStrsHiKveJv9Q4X3bWqQFJB4j2FSAN00pVnmbGEvOmmFmLXeUnp0Grkk3bMg5xgWfEzg5y05tDlQ7HzdvtEL8wXKxc2cK2yaxBrDqTUl5xvdECdJO4L/zcotvxUAdlH4d3N3hQ2iIUJ6P7Q4dhQpTP5LHnq3Evu8wyZwiuBonT
    username: AgCdufX+8SN5P/T0G5xJ+Ou/B4rbCX1ScGYY72IccUBVXW3YWJ2YmMzPSKMCkEO9chcdc+6gDAhKLseQkco+hKdUUKtpUqCOyd07hIhVhQoM3PZTszxkgGr0B/qy09EJf4mY0dgwgY6iAUVgALa7Z8A+9FouyzeJTCNxhdzqNxLP9n31Lh67Pbic3LxwhIwsSzzKOOL4kI+iQipC00BwGu6w5xSDg0Sr5+Lf+RWz/Nh67qdyKGcHyKGRTEjxMVT3kU6e/iur8lkWq0xJknJmw4PLDYhFpC03wJ1na2zdRgqykuUd8GNOudqu6Lhxzb1utbAtm7ukEwbazxPuKoId4a90JwCRQCekKznrDYG+tV9IW1AS4QiZ9lUYnyyeKVFyMwQ0g+XBYCkWpz4WRgF6mmPSplDDt2NfyHOcA74vRlsaUJqjqv4CrD5JxYaEBIcngaBBBwJQYOpXiBl9a1BM+T32lRjHh2LHuzzNZ3tKHp/mKT3krZDD3DM0z4QiyvfVK039qf4u2ETPjtn01uHmCinEMPfXZT2vxz7ayhF+hVlSr4BeMZvj0EmeR4gnhh52NXO1bd0mSyJ3OqonDNmLZRpWDMkbXYKdHAi10fLcIb6FX49u2Qttf9jVdWPDdJ/y1pYsywZoLlL+726qbNeXYyZQu63G4A5Vm+1u6TN9xM+BBAEqrTR2wio5ZAlIeblp7J1D7ujY/lA=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-host-basic-auth-token
      namespace: cicd
    type: kubernetes.io/basic-auth
