apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCpnAbRf4FV5PGvKNFX8yBhnJM3QCiF8vQ61VY3TCgciawCJVhvCtlA2ToFbEwfZS0Ty9CJ1SC4yy18gGMjB0tISHGqZbXFdGoTh9ScgXUkvL50oqnc/or7O06kyI491NPTMfaiUbwWwGTpu53EJwhWWg9VIEVBPO/nsuRbjNsrHDk8JoWdB43nJMY9pwySSP8VM+ml1WkRSKjZkXCt+xf8uTCVtFDgGyXbp8dflFY5icQJqFHrTfS//rBExYRIt5LG4gpJpD8mhsyhakfE54nBxNaq1vCJ59bB6cVsAF28HrwuzT2xm8Veu75b8HL1MyFN9vvbwOnkSpdT+ecgrOz5rNV+D1rJV9jk42gWVuaJgAcI7Avfq97QP15ZqR9WrsGXXOhE4CF2ybL48PFO2D6SZj8N6VuqjVpAUR6P2EeFr3rLybkLQ76qt9Pd5ZCNRkuMzllZxCHaqfplzcplAR2hFAaPWB119i48a+sUjrzYe7yQtCxpfUQv+W33GeM+j1PrPDv9g0wob5i4XP+G41mbo/pMjqN91TjiKiCuQB7x6khUyFSrssEAhffRdXhqt2DGGqwmdt/GIyrQaCb98C3QpMjduV/C66jF98r69/PUEra736bnZESpzd2GZc3oyx2RMM5aac2bgSEK4qKvTlV6ydXOanscWTm+FFeHCKbPLGfflm/32XwOgapRyYGkzM93PLJ8XkQ3615xJRNojbsNAt/ORA==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
