apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgBcDVkCCrnAyRxjYjSO1i4Unjc6ci/cyG1aQ0QKQWrV+0zjdpihZsyfISoOp7Jy0jtq5jNVJzSYUZuF1OpKfXGZubYjtmugeTICTlujIprHynO2rYKM7OsENJw7FkfPjxtb1ZKhBcMInKOD2yw8daXKJGyThnDQRSUlT5DhRTzXosXObdfhNLA6Ag7P4n5A3BGTjozjz26IoxTDmlghciMlo8p27u3BdjChlSvfkr7iabxvZ4GSoBZGjSHMUAfqjg4ZsXwid45zMW3vUs+1SNH3gPad1kaW1oZasYqGfIcVpwg6goV9TiPTacMQV3VX6R2sY4BXvtjNZsq6q+jpGtxPZ41HIRPtzM8pfZodQE3LhBi/PBBFVjnmJOwSa4K8FPoDKviqcuNUDJUHnLgHXYxSWZWthiThIJW6Oi9ylka3xQDQPSpTXeGsccSRD5OR2qWLXViEEkCnY7QAsNrLNs987lY6ta5KUOb0HDCdIqz59zBrEZ5ZH78XZYWBKNKVSd2DeDhZXSOKhVZFTt9X+bjru1SRgGXG34DKzUrXDUALIC9yiSIKzNhevPBU7xpdpsqxSyKAKH+Z/eNvazstQbFanZ2JWoSOeYkLIlxxQBBL4jwQIrRExluzbgtwIAQh9ks7/4gKT6me9C/LciGfWaZFfbOcmAxxSXA47VJIcwJ5DO44PzLiXJVEjWAiPn5h2n6wbCk/h/Qa6e7fGAw3gh3wYhlNbg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
